version: '3'
services:
  web:
    image: "lchang2190/orderservice:node"
    links:
      - cassandra
    ports: 
      - "8080:8080"
    volumes:
      - "/usr/src/orderService"
      //map "ec2url:dockerurl"

  cassandra:
    image: "lchang2190/orderservice:cassandra"
    ports:
      - "9160:9160"
    volumes:
      - "/usr/src/cassandra"
